### ISSUE TITLE
Notion unable to retrieve any 

### ISSUE THREAD

**Issue by MrCredible** [DominiqueGarmier/notion-graph#32]
Not able to retrieve any information from my notion.

Response always comes back empty when POST to Notion search API

```
Connected to pydev debugger (build 232.9559.58)
 * Serving Flask app 'graph'
 * Debug mode: off
DEBUG:asyncio:Using proactor: IocpProactor
INFO:__main__:refreshing graph...
DEBUG:__main__:getting page ids...
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.244:8080
INFO:werkzeug:Press CTRL+C to quit
DEBUG:__main__:work done, cancelling workers...
INFO:__main__:done: 0, failed: 0

```

**Comment by dominiquegarmier** [comment]
It looks like you might have created an integration but have not given it access to any pages. Have you made sure that your Notion pages are shared with the integration? (see the notion docs: https://www.notion.com/my-integrations)

Once you have created the integration make sure to check the following:

- on the root page click the three dots in the top right:
![image](https://github.com/dominiquegarmier/notion-graph/assets/42445422/73f8d76e-65d4-4df7-9991-a370bd70e790)

- at the bottom of that menu you should see your integration (mine is called "graph", the name doesn't matter):
![image](https://github.com/dominiquegarmier/notion-graph/assets/42445422/660cd9e7-b9ff-4c17-a0d9-d76fc51d8ee7)

Otherwise, have you tried to use the api manually? What happens then?

**Comment by MrCredible** [comment]
@dominiquegarmier , ah yes... I forgot about this... been awhile since I have added an integration to Notion. This fixed the issue.
